baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'harrison.tech'

[[menus.main]]
name = "hi, i'm harrison"
pageRef = '/'
weight = 10
  [menus.main.params]
  class = 'lead'


[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
