baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'harrison.tech'

[params]
  greeting = "hi, i'm harrison"

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

# [[menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
